# Generated by Django 2.0.1 on 2018-03-12 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_acao_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensagem',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='upload',
        ),
        migrations.AddField(
            model_name='monitor',
            name='log',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Log'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado'),
        ),
    ]
