# Generated by Django 2.0.1 on 2018-03-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180312_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='created',
            field=models.DateTimeField(verbose_name='Criado'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='created',
            field=models.DateTimeField(verbose_name='Criado'),
        ),
        migrations.AlterField(
            model_name='status',
            name='created',
            field=models.DateTimeField(verbose_name='Criado'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.TextField(blank=True, verbose_name='Status'),
        ),
    ]
