# Generated by Django 2.0.1 on 2018-03-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180314_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_max', models.FloatField(verbose_name='Temp_Max')),
                ('temp_min', models.FloatField(verbose_name='Temp_Min')),
                ('umid_max', models.FloatField(verbose_name='Umid_Max')),
                ('umid_min', models.FloatField(verbose_name='Umid_Min')),
                ('created', models.DateTimeField(verbose_name='Criado')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
