# Generated by Django 2.0.1 on 2018-03-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='acao',
            field=models.IntegerField(verbose_name='Acao'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.IntegerField(blank=True, verbose_name='Status'),
        ),
    ]
