# Generated by Django 2.0.1 on 2018-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180318_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, verbose_name='Status')),
                ('acao', models.IntegerField(blank=True, verbose_name='Acao')),
                ('created', models.DateTimeField(verbose_name='Created')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
