# Generated by Django 2.0.1 on 2018-03-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180320_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='acao',
            field=models.TextField(verbose_name='Acao'),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.TextField(verbose_name='Status'),
        ),
    ]
