# Generated by Django 2.0.1 on 2018-04-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180320_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='umid_max',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='umid_min',
        ),
    ]
