# Generated by Django 2.0.1 on 2018-04-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20180403_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='local',
            field=models.IntegerField(blank=True, default=0, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='status',
            name='manual',
            field=models.IntegerField(blank=True, default=0, verbose_name='Manual'),
        ),
    ]
